language: ruby
cache: bundler

env:
  global:
    - CF_USER=ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
    - CF_ORG=govuk-verify
    - CF_SPACE=docs
    - RUNNING_ON_TRAVIS=true
    - secure: "kcoVgGoAFEDjD8F2/uJU6hUY2L2at28CYa6t/SDou9YHExCHS97C2xkNVba1EGaC/53usXQXpIdA1Z1DfLphyjezUL4OouRo4f3GPOXvqEH+l8KyjcMr6FjH+MH3+voqbxOY5goRRQwvFSwTO0PDsA+odzUG1LcikVgIbd6+FhF/qjZVNan+mMDyvMMPOC56yZW/TkgYE8QHYzex5rhh3z1+nuz45I0sxKA5ujN526dKh8gSv//t8RjtCxxjUg7nkagw3DNQO8VM7wb/qaZO6Jk7Gcde6CDIIanKkfPjHkxa4gDP1yY4TVBMcT+15zgV1pRoUPTjRdT7cCd0DN/LtXgM3wRWwUOnfr7EAV0U7FYMDy9J+7oAtCaM0em+z/FQupoKrkDUJT07aaOE3z5YyGL9kGSlN5ekeNEbBdhbdIeAXECXwMsnBD2izI7mtHbJhtdlRrvblfdUJUzmR3nxTxDQF7Z8YDsJhf8dyK5bd8/nXAxEb1ojneDuPTlxolzrgo1++TtoWLquzrPffs9tIAl/M9Z1Vz+McK+XxluZsO4/OikdxuHB7wrztBlhxkHfcZFnL2d5X6+BW8iYvkoSxXUSdu9SDBd/VJEl/PdGzj8tVE7OE1DpIk0chZ9EP8N7t6rvHtMDyjBf0zWuLqm7y9IIoOFGwe6bSkN88WRmO5M="

before_script:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install cf-cli

script: bundle exec middleman build

deploy:
  skip_cleanup: true
  provider: script
  script: "./script/deploy"
  on:
    branch: master
