language: ruby
cache: bundler

env:
  global:
    - CF_USER=ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
    - CF_ORG=govuk-verify
    - CF_SPACE=docs
    - RUNNING_ON_TRAVIS=true
    - secure: "BDUmMeeTEaMLcxxgcKXppuQDK4mkVFEf473wEK+9jQyz/3VNgQUqBOPoRm0DptpRBzzZk6X7dcBikchGWBImu2qPRSU4kqTTu6C6IHVb7kw+uE1RfozTRa2M9sO/mxFVaWgv6EieqVAsXNfzCCZ/w6J9haNvm0ZDvtHdRvV//cyZOEu9BKol9gobr7q0pILyPkzaC7uNgOFUke4d1NIYfCN6k7zJWBKCGHDHyi4YC2I95KCUZ9IUIt9c9/BNY3OM4VfYG6yS7fE/0iWEb0Ik2nt8tWzIhvv7nzBXl2XUi1Rm62H5lwT4OsG68bfiqd58r+nbqLcJfch4vgtV/968XTS6H2cLYJWiWtVAGBh1EUfkYZB+DvDANIMMMEXMztHAPFz7PjsiRS1d/0/pEz5ITLkW4Q5d1rkc5eiOYvbMEJytbz7CxlnSAGM6LlCEXYlQjiWmNly/S7VFaRZKjslLX9P2k4RVhhbHtCJqQ/TaXvu4Bez+114HpUiy/nzVn6yfcGxRvWRd4wfg6pcW+FkfjCNBXAfBYVM/5YN6v+VRy8JfLH/XJR705JTnHpGV6m/kO2l2swTWKFNT8vhJn2q+wJdBtnFsibMnLPA+aBSDmCTeerL6VeV2mnQmySk/AncIRBYyj/4p/FSm1bZb3wdVvGvppKkWF0RglkDUK1XYOtk="

before_script:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install cf-cli

script: bundle exec middleman build

deploy:
  skip_cleanup: true
  provider: script
  script: "./script/deploy"
  on:
    branch: master
