language: ruby
cache: bundler
script: bundle exec middleman build
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
  password:
    secure: g0vkgqF5SYENYG+fSEaeZzHRLWMBvhQefyjs2xWy708Nh5eO+3+Wyg2GCMltZHnFfhiasbGBtn3bwgOfuV1JLFwWkuOi5SdpUoEEXrZ5DcOXuwaInBnO8I6bSvSQpqjfYAhmuRA2Z4NuV6xDZI08wRZRphccccyuCRf6WFXAkSEEJzKMOD/7JNlv6TS9491BK0Hx4x16ZWk0l3JdMLt7y+vYyrm02t9+VauOntYfJcfeLO6NX0J6YU6vJzb1C0RcfrOSgyI73MgK5m9gHYqUVIV8AzwMBEiGzsbNGMQBK/qYgO4ETCLDBxqftgULbB3KT8t6G+CuecOgVRlJQZk/dkDuoodfP4u4hZa3nM9ZnM7KAa51KXkfmoMUXwyjs0qcDTCiBI8VMaNcMIIU45BWdF4ND1b3qLYs+BPuoxKM5EgMzCFh8Dn5NyjNA/zOZbUZdgekWKSqdf8932nWQsVGxZGn1wVs7Jrx04d5J2cckYz2j88LGLUQayLcLuODhFVS8q0JwxxRLJ27i6/C/8wU6D150OkywoivlmtTzJ1fcvSdwQverzGYgk2RN+GWQJ3gABZv5hXVjvMTs/5TZD4Lr7BZrNJw+dvYqBiwCkNFlwDIYx0k0FikRe7ZAk16X6zWwo1digcP3d1grbFHXKZ7nP6F7JcKXb8atBBroCPDpvE=
  organization: govuk-verify
  space: docs
  on:
    repo: alphagov/verify-tech-docs
