language: ruby
cache: bundler

script: bundle exec middleman build

deploy:
  provider: cloudfoundry
  username: ida-operations+paas-build-bot@digital.cabinet-office.gov.uk
  password:
    secure: "pV0AerCqKlcr/yaBTvfJcwdIJaqYNYRts+So4D2ySpRakXbLbDbKdYOkwv1GeIWKaX1uF3CXVSKxzFbnGePsmjAr5eZ0Cqorp8UikylizV04ootYzr8C5/uhXeIL7U/dcwYr84QBypIuYq0rngIAn4WtFi+qaqxTp1USPM5/1KJiyPZrnsBm+4laomplvAD9jFn7H8qDhdOkafn/r5BfzsbPLqYXclsv/kDaWf2reszBVYtk/6Nmp6lZ4unonspjsduDrHRu2FTNsPLtfeV7FWshveKKXvnlj2ZakelLfV9xs5qDaHfoD6JZVar1kkPA757Ys935DyiuoR1hSEBAJp8fBngN5CZAJwxrLMjnbFtXUu6cCvyMcfHB27Qb0ECWLTX5Q4X3b9Xe3k55m9tf+PQ5wpnN16suLALyqMZN5aztlHPS3Wt8JA+IsKZe4QJBerkBFuTbUuiqn4xNAJH4zsaaTRdmA1H6APCmtzocr/RJ9/+KRkY3glhbgXaI2LwYfFDSZooLNPaDxwq2wyDc2FYTEaZ+V0du8CKWiF1yEyN4amuJcki2RtzJkjsOcTn2VKYGoEiNjmCmXCI2TeKkplILiyRM7YtLU3Yj6XI87Bwt2mEDrfVxFTazjRpY6C4kB1YIQ42Yk+7Dz53JHLqXFYi/pJqNVsQvhn1LPioAddA="
  api: https://api.cloud.service.gov.uk
  organization: govuk-verify
  space: docs
  manifest: manifest.yml
